/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.11.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SMSWorks.Api.Model;
using SMSWorks.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SMSWorks.Api.Test.Model
{
    /// <summary>
    ///  Class for testing CountryResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CountryResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CountryResponse
        //private CountryResponse instance;

        public CountryResponseTests()
        {
            // TODO uncomment below to create an instance of CountryResponse
            //instance = new CountryResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CountryResponse
        /// </summary>
        [Fact]
        public void CountryResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CountryResponse
            //Assert.IsType<CountryResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'Credits'
        /// </summary>
        [Fact]
        public void CreditsTest()
        {
            // TODO unit test for the property 'Credits'
        }
    }
}
