/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.11.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SMSWorks.Api.Model;
using SMSWorks.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SMSWorks.Api.Test.Model
{
    /// <summary>
    ///  Class for testing MessageVolumeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessageVolumeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MessageVolumeResponse
        //private MessageVolumeResponse instance;

        public MessageVolumeResponseTests()
        {
            // TODO uncomment below to create an instance of MessageVolumeResponse
            //instance = new MessageVolumeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessageVolumeResponse
        /// </summary>
        [Fact]
        public void MessageVolumeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MessageVolumeResponse
            //Assert.IsType<MessageVolumeResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Volume'
        /// </summary>
        [Fact]
        public void VolumeTest()
        {
            // TODO unit test for the property 'Volume'
        }
    }
}
