/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.11.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CountryResponse
    /// </summary>
    [DataContract]
    public partial class CountryResponse :  IEquatable<CountryResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CountryResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CountryResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CountryResponse" /> class.
        /// </summary>
        /// <param name="code">The country code supplied in the API call..</param>
        /// <param name="country">The name of the country..</param>
        /// <param name="credits">The number of credits required to send an SMS to the country code provided. Floating point number. (required).</param>
        public CountryResponse(string code = default(string), string country = default(string), decimal credits = default(decimal))
        {
            // to ensure "credits" is required (not null)
            if (credits == null)
            {
                throw new InvalidDataException("credits is a required property for CountryResponse and cannot be null");
            }
            else
            {
                this.Credits = credits;
            }

            this.Code = code;
            this.Country = country;
        }

        /// <summary>
        /// The country code supplied in the API call.
        /// </summary>
        /// <value>The country code supplied in the API call.</value>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// The name of the country.
        /// </summary>
        /// <value>The name of the country.</value>
        [DataMember(Name="country", EmitDefaultValue=false)]
        public string Country { get; set; }

        /// <summary>
        /// The number of credits required to send an SMS to the country code provided. Floating point number.
        /// </summary>
        /// <value>The number of credits required to send an SMS to the country code provided. Floating point number.</value>
        [DataMember(Name="credits", EmitDefaultValue=true)]
        public decimal Credits { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CountryResponse {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Credits: ").Append(Credits).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CountryResponse);
        }

        /// <summary>
        /// Returns true if CountryResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CountryResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CountryResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.Country == input.Country ||
                    (this.Country != null &&
                    this.Country.Equals(input.Country))
                ) && 
                (
                    this.Credits == input.Credits ||
                    (this.Credits != null &&
                    this.Credits.Equals(input.Credits))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.Country != null)
                    hashCode = hashCode * 59 + this.Country.GetHashCode();
                if (this.Credits != null)
                    hashCode = hashCode * 59 + this.Credits.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
