/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * The version of the OpenAPI document: 1.7.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing MessagesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MessagesApiTests : IDisposable
    {
        private MessagesApi instance;

        public MessagesApiTests()
        {
            instance = new MessagesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessagesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MessagesApi
            //Assert.IsType<MessagesApi>(instance);
        }

        /// <summary>
        /// Test CancelScheduledJob
        /// </summary>
        [Fact]
        public void CancelScheduledJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string messageid = null;
            //var response = instance.CancelScheduledJob(messageid);
            //Assert.IsType<CancelledMessageResponse>(response);
        }

        /// <summary>
        /// Test DeleteMessage
        /// </summary>
        [Fact]
        public void DeleteMessageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string messageid = null;
            //var response = instance.DeleteMessage(messageid);
            //Assert.IsType<DeletedMessageResponse>(response);
        }

        /// <summary>
        /// Test GetFailedMessages
        /// </summary>
        [Fact]
        public void GetFailedMessagesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Query query = null;
            //var response = instance.GetFailedMessages(query);
            //Assert.IsType<List<MessageResponse>>(response);
        }

        /// <summary>
        /// Test GetInboxMessages
        /// </summary>
        [Fact]
        public void GetInboxMessagesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Query query = null;
            //var response = instance.GetInboxMessages(query);
            //Assert.IsType<List<MessageResponse>>(response);
        }

        /// <summary>
        /// Test GetMessageById
        /// </summary>
        [Fact]
        public void GetMessageByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string messageid = null;
            //var response = instance.GetMessageById(messageid);
            //Assert.IsType<MessageResponse>(response);
        }

        /// <summary>
        /// Test GetMessages
        /// </summary>
        [Fact]
        public void GetMessagesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Query query = null;
            //var response = instance.GetMessages(query);
            //Assert.IsType<List<MessageResponse>>(response);
        }

        /// <summary>
        /// Test GetScheduledMessages
        /// </summary>
        [Fact]
        public void GetScheduledMessagesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetScheduledMessages();
            //Assert.IsType<ScheduledMessagesResponse>(response);
        }

        /// <summary>
        /// Test MessageSendPost
        /// </summary>
        [Fact]
        public void MessageSendPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Message smsMessage = null;
            //var response = instance.MessageSendPost(smsMessage);
            //Assert.IsType<SendMessageResponse>(response);
        }

        /// <summary>
        /// Test ScheduleMessage
        /// </summary>
        [Fact]
        public void ScheduleMessageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Message smsMessage = null;
            //var response = instance.ScheduleMessage(smsMessage);
            //Assert.IsType<List<ScheduledMessageResponse>>(response);
        }

        /// <summary>
        /// Test SendFlashMessage
        /// </summary>
        [Fact]
        public void SendFlashMessageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Message smsMessage = null;
            //var response = instance.SendFlashMessage(smsMessage);
            //Assert.IsType<SendMessageResponse>(response);
        }
    }
}
