/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.11.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUtilsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get error by code
        /// </summary>
        /// <remarks>
        /// Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <returns>ExtendedErrorModel</returns>
        ExtendedErrorModel UtilsErrorsErrorcodeGet (string errorcode);

        /// <summary>
        /// Get error by code
        /// </summary>
        /// <remarks>
        /// Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <returns>ApiResponse of ExtendedErrorModel</returns>
        ApiResponse<ExtendedErrorModel> UtilsErrorsErrorcodeGetWithHttpInfo (string errorcode);
        /// <summary>
        /// Return the customer ID to the caller
        /// </summary>
        /// <remarks>
        /// A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>TestResponse</returns>
        TestResponse UtilsTestGet ();

        /// <summary>
        /// Return the customer ID to the caller
        /// </summary>
        /// <remarks>
        /// A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of TestResponse</returns>
        ApiResponse<TestResponse> UtilsTestGetWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get error by code
        /// </summary>
        /// <remarks>
        /// Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ExtendedErrorModel</returns>
        System.Threading.Tasks.Task<ExtendedErrorModel> UtilsErrorsErrorcodeGetAsync (string errorcode, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get error by code
        /// </summary>
        /// <remarks>
        /// Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (ExtendedErrorModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExtendedErrorModel>> UtilsErrorsErrorcodeGetWithHttpInfoAsync (string errorcode, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Return the customer ID to the caller
        /// </summary>
        /// <remarks>
        /// A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of TestResponse</returns>
        System.Threading.Tasks.Task<TestResponse> UtilsTestGetAsync (CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Return the customer ID to the caller
        /// </summary>
        /// <remarks>
        /// A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (TestResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TestResponse>> UtilsTestGetWithHttpInfoAsync (CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UtilsApi : IUtilsApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UtilsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UtilsApi(String basePath)
        {
            this.Configuration = new Org.OpenAPITools.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UtilsApi"/> class
        /// </summary>
        /// <returns></returns>
        public UtilsApi()
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.Default;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UtilsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UtilsApi(Org.OpenAPITools.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Org.OpenAPITools.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get error by code Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <returns>ExtendedErrorModel</returns>
        public ExtendedErrorModel UtilsErrorsErrorcodeGet (string errorcode)
        {
             ApiResponse<ExtendedErrorModel> localVarResponse = UtilsErrorsErrorcodeGetWithHttpInfo(errorcode);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get error by code Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <returns>ApiResponse of ExtendedErrorModel</returns>
        public ApiResponse<ExtendedErrorModel> UtilsErrorsErrorcodeGetWithHttpInfo (string errorcode)
        {
            // verify the required parameter 'errorcode' is set
            if (errorcode == null)
                throw new ApiException(400, "Missing required parameter 'errorcode' when calling UtilsApi->UtilsErrorsErrorcodeGet");

            var localVarPath = "/utils/errors/{errorcode}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (errorcode != null) localVarPathParams.Add("errorcode", this.Configuration.ApiClient.ParameterToString(errorcode)); // path parameter

            // authentication (JWT) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UtilsErrorsErrorcodeGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ExtendedErrorModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ExtendedErrorModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ExtendedErrorModel)));
        }

        /// <summary>
        /// Get error by code Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ExtendedErrorModel</returns>
        public async System.Threading.Tasks.Task<ExtendedErrorModel> UtilsErrorsErrorcodeGetAsync (string errorcode, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<ExtendedErrorModel> localVarResponse = await UtilsErrorsErrorcodeGetWithHttpInfoAsync(errorcode, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get error by code Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (ExtendedErrorModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ExtendedErrorModel>> UtilsErrorsErrorcodeGetWithHttpInfoAsync (string errorcode, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'errorcode' is set
            if (errorcode == null)
                throw new ApiException(400, "Missing required parameter 'errorcode' when calling UtilsApi->UtilsErrorsErrorcodeGet");

            var localVarPath = "/utils/errors/{errorcode}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (errorcode != null) localVarPathParams.Add("errorcode", this.Configuration.ApiClient.ParameterToString(errorcode)); // path parameter

            // authentication (JWT) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UtilsErrorsErrorcodeGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ExtendedErrorModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ExtendedErrorModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ExtendedErrorModel)));
        }

        /// <summary>
        /// Return the customer ID to the caller A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>TestResponse</returns>
        public TestResponse UtilsTestGet ()
        {
             ApiResponse<TestResponse> localVarResponse = UtilsTestGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Return the customer ID to the caller A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of TestResponse</returns>
        public ApiResponse<TestResponse> UtilsTestGetWithHttpInfo ()
        {

            var localVarPath = "/utils/test";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (JWT) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UtilsTestGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TestResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TestResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TestResponse)));
        }

        /// <summary>
        /// Return the customer ID to the caller A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of TestResponse</returns>
        public async System.Threading.Tasks.Task<TestResponse> UtilsTestGetAsync (CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<TestResponse> localVarResponse = await UtilsTestGetWithHttpInfoAsync(cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Return the customer ID to the caller A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (TestResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TestResponse>> UtilsTestGetWithHttpInfoAsync (CancellationToken cancellationToken = default(CancellationToken))
        {

            var localVarPath = "/utils/test";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (JWT) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UtilsTestGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TestResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TestResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TestResponse)));
        }

    }
}
