/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.11.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using SMSWorks.Api.Client;
using SMSWorks.Api.Model;

namespace SMSWorks.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBatchMessagesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Send a collection of unique SMS messages
        /// </summary>
        /// <remarks>
        /// Batches may contain up to 5000 messages at a time.
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messages">An array of messages</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchMessageResponse</returns>
        BatchMessageResponse BatchAnyPost(Object messages, int operationIndex = 0);

        /// <summary>
        /// Send a collection of unique SMS messages
        /// </summary>
        /// <remarks>
        /// Batches may contain up to 5000 messages at a time.
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messages">An array of messages</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchMessageResponse</returns>
        ApiResponse<BatchMessageResponse> BatchAnyPostWithHttpInfo(Object messages, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve all messages with the given batch ID
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;MessageResponse&gt;</returns>
        List<MessageResponse> BatchBatchidGet(string batchid, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve all messages with the given batch ID
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;MessageResponse&gt;</returns>
        ApiResponse<List<MessageResponse>> BatchBatchidGetWithHttpInfo(string batchid, int operationIndex = 0);
        /// <summary>
        /// Schedule a batch of SMS messages
        /// </summary>
        /// <remarks>
        /// Schedules a batch of SMS messages to be sent at the date/time you specify
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ScheduledBatchResponse</returns>
        ScheduledBatchResponse BatchSchedulePost(BatchMessage smsMessage, int operationIndex = 0);

        /// <summary>
        /// Schedule a batch of SMS messages
        /// </summary>
        /// <remarks>
        /// Schedules a batch of SMS messages to be sent at the date/time you specify
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ScheduledBatchResponse</returns>
        ApiResponse<ScheduledBatchResponse> BatchSchedulePostWithHttpInfo(BatchMessage smsMessage, int operationIndex = 0);
        /// <summary>
        /// Send an SMS message to multiple recipients
        /// </summary>
        /// <remarks>
        /// Batches may contain up to 5000 messages at a time
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchMessageResponse</returns>
        BatchMessageResponse BatchSendPost(BatchMessage smsMessage, int operationIndex = 0);

        /// <summary>
        /// Send an SMS message to multiple recipients
        /// </summary>
        /// <remarks>
        /// Batches may contain up to 5000 messages at a time
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchMessageResponse</returns>
        ApiResponse<BatchMessageResponse> BatchSendPostWithHttpInfo(BatchMessage smsMessage, int operationIndex = 0);
        /// <summary>
        /// Cancel a scheduled batch
        /// </summary>
        /// <remarks>
        /// Cancels a batch of scheduled messages using the supplied batch ID
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CancelledMessageResponse</returns>
        CancelledMessageResponse BatchesScheduleBatchidDelete(string batchid, int operationIndex = 0);

        /// <summary>
        /// Cancel a scheduled batch
        /// </summary>
        /// <remarks>
        /// Cancels a batch of scheduled messages using the supplied batch ID
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CancelledMessageResponse</returns>
        ApiResponse<CancelledMessageResponse> BatchesScheduleBatchidDeleteWithHttpInfo(string batchid, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBatchMessagesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Send a collection of unique SMS messages
        /// </summary>
        /// <remarks>
        /// Batches may contain up to 5000 messages at a time.
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messages">An array of messages</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchMessageResponse</returns>
        System.Threading.Tasks.Task<BatchMessageResponse> BatchAnyPostAsync(Object messages, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Send a collection of unique SMS messages
        /// </summary>
        /// <remarks>
        /// Batches may contain up to 5000 messages at a time.
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messages">An array of messages</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchMessageResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BatchMessageResponse>> BatchAnyPostWithHttpInfoAsync(Object messages, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve all messages with the given batch ID
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;MessageResponse&gt;</returns>
        System.Threading.Tasks.Task<List<MessageResponse>> BatchBatchidGetAsync(string batchid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve all messages with the given batch ID
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;MessageResponse&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<MessageResponse>>> BatchBatchidGetWithHttpInfoAsync(string batchid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Schedule a batch of SMS messages
        /// </summary>
        /// <remarks>
        /// Schedules a batch of SMS messages to be sent at the date/time you specify
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ScheduledBatchResponse</returns>
        System.Threading.Tasks.Task<ScheduledBatchResponse> BatchSchedulePostAsync(BatchMessage smsMessage, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Schedule a batch of SMS messages
        /// </summary>
        /// <remarks>
        /// Schedules a batch of SMS messages to be sent at the date/time you specify
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ScheduledBatchResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ScheduledBatchResponse>> BatchSchedulePostWithHttpInfoAsync(BatchMessage smsMessage, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Send an SMS message to multiple recipients
        /// </summary>
        /// <remarks>
        /// Batches may contain up to 5000 messages at a time
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchMessageResponse</returns>
        System.Threading.Tasks.Task<BatchMessageResponse> BatchSendPostAsync(BatchMessage smsMessage, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Send an SMS message to multiple recipients
        /// </summary>
        /// <remarks>
        /// Batches may contain up to 5000 messages at a time
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchMessageResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BatchMessageResponse>> BatchSendPostWithHttpInfoAsync(BatchMessage smsMessage, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Cancel a scheduled batch
        /// </summary>
        /// <remarks>
        /// Cancels a batch of scheduled messages using the supplied batch ID
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CancelledMessageResponse</returns>
        System.Threading.Tasks.Task<CancelledMessageResponse> BatchesScheduleBatchidDeleteAsync(string batchid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Cancel a scheduled batch
        /// </summary>
        /// <remarks>
        /// Cancels a batch of scheduled messages using the supplied batch ID
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CancelledMessageResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CancelledMessageResponse>> BatchesScheduleBatchidDeleteWithHttpInfoAsync(string batchid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBatchMessagesApi : IBatchMessagesApiSync, IBatchMessagesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BatchMessagesApi : IBatchMessagesApi
    {
        private SMSWorks.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchMessagesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BatchMessagesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchMessagesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BatchMessagesApi(string basePath)
        {
            this.Configuration = SMSWorks.Api.Client.Configuration.MergeConfigurations(
                SMSWorks.Api.Client.GlobalConfiguration.Instance,
                new SMSWorks.Api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = SMSWorks.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchMessagesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public BatchMessagesApi(SMSWorks.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = SMSWorks.Api.Client.Configuration.MergeConfigurations(
                SMSWorks.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = SMSWorks.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchMessagesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public BatchMessagesApi(SMSWorks.Api.Client.ISynchronousClient client, SMSWorks.Api.Client.IAsynchronousClient asyncClient, SMSWorks.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = SMSWorks.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public SMSWorks.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public SMSWorks.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SMSWorks.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SMSWorks.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Send a collection of unique SMS messages Batches may contain up to 5000 messages at a time.
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messages">An array of messages</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchMessageResponse</returns>
        public BatchMessageResponse BatchAnyPost(Object messages, int operationIndex = 0)
        {
            SMSWorks.Api.Client.ApiResponse<BatchMessageResponse> localVarResponse = BatchAnyPostWithHttpInfo(messages);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Send a collection of unique SMS messages Batches may contain up to 5000 messages at a time.
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messages">An array of messages</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchMessageResponse</returns>
        public SMSWorks.Api.Client.ApiResponse<BatchMessageResponse> BatchAnyPostWithHttpInfo(Object messages, int operationIndex = 0)
        {
            // verify the required parameter 'messages' is set
            if (messages == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'messages' when calling BatchMessagesApi->BatchAnyPost");
            }

            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = messages;

            localVarRequestOptions.Operation = "BatchMessagesApi.BatchAnyPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BatchMessageResponse>("/batch/any", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BatchAnyPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Send a collection of unique SMS messages Batches may contain up to 5000 messages at a time.
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messages">An array of messages</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchMessageResponse</returns>
        public async System.Threading.Tasks.Task<BatchMessageResponse> BatchAnyPostAsync(Object messages, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            SMSWorks.Api.Client.ApiResponse<BatchMessageResponse> localVarResponse = await BatchAnyPostWithHttpInfoAsync(messages, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Send a collection of unique SMS messages Batches may contain up to 5000 messages at a time.
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messages">An array of messages</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchMessageResponse)</returns>
        public async System.Threading.Tasks.Task<SMSWorks.Api.Client.ApiResponse<BatchMessageResponse>> BatchAnyPostWithHttpInfoAsync(Object messages, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'messages' is set
            if (messages == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'messages' when calling BatchMessagesApi->BatchAnyPost");
            }


            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = messages;

            localVarRequestOptions.Operation = "BatchMessagesApi.BatchAnyPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<BatchMessageResponse>("/batch/any", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BatchAnyPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Retrieve all messages with the given batch ID
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;MessageResponse&gt;</returns>
        public List<MessageResponse> BatchBatchidGet(string batchid, int operationIndex = 0)
        {
            SMSWorks.Api.Client.ApiResponse<List<MessageResponse>> localVarResponse = BatchBatchidGetWithHttpInfo(batchid);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Retrieve all messages with the given batch ID
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;MessageResponse&gt;</returns>
        public SMSWorks.Api.Client.ApiResponse<List<MessageResponse>> BatchBatchidGetWithHttpInfo(string batchid, int operationIndex = 0)
        {
            // verify the required parameter 'batchid' is set
            if (batchid == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'batchid' when calling BatchMessagesApi->BatchBatchidGet");
            }

            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("batchid", SMSWorks.Api.Client.ClientUtils.ParameterToString(batchid)); // path parameter

            localVarRequestOptions.Operation = "BatchMessagesApi.BatchBatchidGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<MessageResponse>>("/batch/{batchid}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BatchBatchidGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Retrieve all messages with the given batch ID
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;MessageResponse&gt;</returns>
        public async System.Threading.Tasks.Task<List<MessageResponse>> BatchBatchidGetAsync(string batchid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            SMSWorks.Api.Client.ApiResponse<List<MessageResponse>> localVarResponse = await BatchBatchidGetWithHttpInfoAsync(batchid, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Retrieve all messages with the given batch ID
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;MessageResponse&gt;)</returns>
        public async System.Threading.Tasks.Task<SMSWorks.Api.Client.ApiResponse<List<MessageResponse>>> BatchBatchidGetWithHttpInfoAsync(string batchid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'batchid' is set
            if (batchid == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'batchid' when calling BatchMessagesApi->BatchBatchidGet");
            }


            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("batchid", SMSWorks.Api.Client.ClientUtils.ParameterToString(batchid)); // path parameter

            localVarRequestOptions.Operation = "BatchMessagesApi.BatchBatchidGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<MessageResponse>>("/batch/{batchid}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BatchBatchidGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Schedule a batch of SMS messages Schedules a batch of SMS messages to be sent at the date/time you specify
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ScheduledBatchResponse</returns>
        public ScheduledBatchResponse BatchSchedulePost(BatchMessage smsMessage, int operationIndex = 0)
        {
            SMSWorks.Api.Client.ApiResponse<ScheduledBatchResponse> localVarResponse = BatchSchedulePostWithHttpInfo(smsMessage);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Schedule a batch of SMS messages Schedules a batch of SMS messages to be sent at the date/time you specify
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ScheduledBatchResponse</returns>
        public SMSWorks.Api.Client.ApiResponse<ScheduledBatchResponse> BatchSchedulePostWithHttpInfo(BatchMessage smsMessage, int operationIndex = 0)
        {
            // verify the required parameter 'smsMessage' is set
            if (smsMessage == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'smsMessage' when calling BatchMessagesApi->BatchSchedulePost");
            }

            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = smsMessage;

            localVarRequestOptions.Operation = "BatchMessagesApi.BatchSchedulePost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ScheduledBatchResponse>("/batch/schedule", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BatchSchedulePost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Schedule a batch of SMS messages Schedules a batch of SMS messages to be sent at the date/time you specify
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ScheduledBatchResponse</returns>
        public async System.Threading.Tasks.Task<ScheduledBatchResponse> BatchSchedulePostAsync(BatchMessage smsMessage, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            SMSWorks.Api.Client.ApiResponse<ScheduledBatchResponse> localVarResponse = await BatchSchedulePostWithHttpInfoAsync(smsMessage, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Schedule a batch of SMS messages Schedules a batch of SMS messages to be sent at the date/time you specify
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ScheduledBatchResponse)</returns>
        public async System.Threading.Tasks.Task<SMSWorks.Api.Client.ApiResponse<ScheduledBatchResponse>> BatchSchedulePostWithHttpInfoAsync(BatchMessage smsMessage, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'smsMessage' is set
            if (smsMessage == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'smsMessage' when calling BatchMessagesApi->BatchSchedulePost");
            }


            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = smsMessage;

            localVarRequestOptions.Operation = "BatchMessagesApi.BatchSchedulePost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ScheduledBatchResponse>("/batch/schedule", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BatchSchedulePost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Send an SMS message to multiple recipients Batches may contain up to 5000 messages at a time
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchMessageResponse</returns>
        public BatchMessageResponse BatchSendPost(BatchMessage smsMessage, int operationIndex = 0)
        {
            SMSWorks.Api.Client.ApiResponse<BatchMessageResponse> localVarResponse = BatchSendPostWithHttpInfo(smsMessage);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Send an SMS message to multiple recipients Batches may contain up to 5000 messages at a time
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchMessageResponse</returns>
        public SMSWorks.Api.Client.ApiResponse<BatchMessageResponse> BatchSendPostWithHttpInfo(BatchMessage smsMessage, int operationIndex = 0)
        {
            // verify the required parameter 'smsMessage' is set
            if (smsMessage == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'smsMessage' when calling BatchMessagesApi->BatchSendPost");
            }

            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = smsMessage;

            localVarRequestOptions.Operation = "BatchMessagesApi.BatchSendPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BatchMessageResponse>("/batch/send", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BatchSendPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Send an SMS message to multiple recipients Batches may contain up to 5000 messages at a time
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchMessageResponse</returns>
        public async System.Threading.Tasks.Task<BatchMessageResponse> BatchSendPostAsync(BatchMessage smsMessage, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            SMSWorks.Api.Client.ApiResponse<BatchMessageResponse> localVarResponse = await BatchSendPostWithHttpInfoAsync(smsMessage, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Send an SMS message to multiple recipients Batches may contain up to 5000 messages at a time
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsMessage">Message properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchMessageResponse)</returns>
        public async System.Threading.Tasks.Task<SMSWorks.Api.Client.ApiResponse<BatchMessageResponse>> BatchSendPostWithHttpInfoAsync(BatchMessage smsMessage, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'smsMessage' is set
            if (smsMessage == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'smsMessage' when calling BatchMessagesApi->BatchSendPost");
            }


            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = smsMessage;

            localVarRequestOptions.Operation = "BatchMessagesApi.BatchSendPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<BatchMessageResponse>("/batch/send", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BatchSendPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Cancel a scheduled batch Cancels a batch of scheduled messages using the supplied batch ID
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CancelledMessageResponse</returns>
        public CancelledMessageResponse BatchesScheduleBatchidDelete(string batchid, int operationIndex = 0)
        {
            SMSWorks.Api.Client.ApiResponse<CancelledMessageResponse> localVarResponse = BatchesScheduleBatchidDeleteWithHttpInfo(batchid);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Cancel a scheduled batch Cancels a batch of scheduled messages using the supplied batch ID
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CancelledMessageResponse</returns>
        public SMSWorks.Api.Client.ApiResponse<CancelledMessageResponse> BatchesScheduleBatchidDeleteWithHttpInfo(string batchid, int operationIndex = 0)
        {
            // verify the required parameter 'batchid' is set
            if (batchid == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'batchid' when calling BatchMessagesApi->BatchesScheduleBatchidDelete");
            }

            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("batchid", SMSWorks.Api.Client.ClientUtils.ParameterToString(batchid)); // path parameter

            localVarRequestOptions.Operation = "BatchMessagesApi.BatchesScheduleBatchidDelete";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<CancelledMessageResponse>("/batches/schedule/{batchid}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BatchesScheduleBatchidDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Cancel a scheduled batch Cancels a batch of scheduled messages using the supplied batch ID
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CancelledMessageResponse</returns>
        public async System.Threading.Tasks.Task<CancelledMessageResponse> BatchesScheduleBatchidDeleteAsync(string batchid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            SMSWorks.Api.Client.ApiResponse<CancelledMessageResponse> localVarResponse = await BatchesScheduleBatchidDeleteWithHttpInfoAsync(batchid, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Cancel a scheduled batch Cancels a batch of scheduled messages using the supplied batch ID
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchid">The ID of the batch you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CancelledMessageResponse)</returns>
        public async System.Threading.Tasks.Task<SMSWorks.Api.Client.ApiResponse<CancelledMessageResponse>> BatchesScheduleBatchidDeleteWithHttpInfoAsync(string batchid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'batchid' is set
            if (batchid == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'batchid' when calling BatchMessagesApi->BatchesScheduleBatchidDelete");
            }


            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("batchid", SMSWorks.Api.Client.ClientUtils.ParameterToString(batchid)); // path parameter

            localVarRequestOptions.Operation = "BatchMessagesApi.BatchesScheduleBatchidDelete";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<CancelledMessageResponse>("/batches/schedule/{batchid}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("BatchesScheduleBatchidDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
