/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.11.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using SMSWorks.Api.Client;
using SMSWorks.Api.Model;

namespace SMSWorks.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICreditsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// The credit balance on your SMS Works account
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CreditsResponse</returns>
        CreditsResponse CreditsBalanceGet(int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// The credit balance on your SMS Works account
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CreditsResponse</returns>
        ApiResponse<CreditsResponse> CreditsBalanceGetWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// The credit cost for each SMS sent to the country code provided
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="countrycode">The 2-letter ISO country code of the country you want to retrieve the credit cost for.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CountryResponse</returns>
        CountryResponse CreditsCountrycodeGet(string countrycode, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// The credit cost for each SMS sent to the country code provided
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="countrycode">The 2-letter ISO country code of the country you want to retrieve the credit cost for.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CountryResponse</returns>
        ApiResponse<CountryResponse> CreditsCountrycodeGetWithHttpInfo(string countrycode, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICreditsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// The credit balance on your SMS Works account
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreditsResponse</returns>
        System.Threading.Tasks.Task<CreditsResponse> CreditsBalanceGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// The credit balance on your SMS Works account
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreditsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreditsResponse>> CreditsBalanceGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// The credit cost for each SMS sent to the country code provided
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="countrycode">The 2-letter ISO country code of the country you want to retrieve the credit cost for.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CountryResponse</returns>
        System.Threading.Tasks.Task<CountryResponse> CreditsCountrycodeGetAsync(string countrycode, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// The credit cost for each SMS sent to the country code provided
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="countrycode">The 2-letter ISO country code of the country you want to retrieve the credit cost for.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CountryResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CountryResponse>> CreditsCountrycodeGetWithHttpInfoAsync(string countrycode, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICreditsApi : ICreditsApiSync, ICreditsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CreditsApi : ICreditsApi
    {
        private SMSWorks.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CreditsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CreditsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreditsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CreditsApi(string basePath)
        {
            this.Configuration = SMSWorks.Api.Client.Configuration.MergeConfigurations(
                SMSWorks.Api.Client.GlobalConfiguration.Instance,
                new SMSWorks.Api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = SMSWorks.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreditsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CreditsApi(SMSWorks.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = SMSWorks.Api.Client.Configuration.MergeConfigurations(
                SMSWorks.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = SMSWorks.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreditsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public CreditsApi(SMSWorks.Api.Client.ISynchronousClient client, SMSWorks.Api.Client.IAsynchronousClient asyncClient, SMSWorks.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = SMSWorks.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public SMSWorks.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public SMSWorks.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SMSWorks.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SMSWorks.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  The credit balance on your SMS Works account
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CreditsResponse</returns>
        public CreditsResponse CreditsBalanceGet(int operationIndex = 0)
        {
            SMSWorks.Api.Client.ApiResponse<CreditsResponse> localVarResponse = CreditsBalanceGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  The credit balance on your SMS Works account
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CreditsResponse</returns>
        public SMSWorks.Api.Client.ApiResponse<CreditsResponse> CreditsBalanceGetWithHttpInfo(int operationIndex = 0)
        {
            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "CreditsApi.CreditsBalanceGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<CreditsResponse>("/credits/balance", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreditsBalanceGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  The credit balance on your SMS Works account
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreditsResponse</returns>
        public async System.Threading.Tasks.Task<CreditsResponse> CreditsBalanceGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            SMSWorks.Api.Client.ApiResponse<CreditsResponse> localVarResponse = await CreditsBalanceGetWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  The credit balance on your SMS Works account
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreditsResponse)</returns>
        public async System.Threading.Tasks.Task<SMSWorks.Api.Client.ApiResponse<CreditsResponse>> CreditsBalanceGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "CreditsApi.CreditsBalanceGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<CreditsResponse>("/credits/balance", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreditsBalanceGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  The credit cost for each SMS sent to the country code provided
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="countrycode">The 2-letter ISO country code of the country you want to retrieve the credit cost for.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CountryResponse</returns>
        public CountryResponse CreditsCountrycodeGet(string countrycode, int operationIndex = 0)
        {
            SMSWorks.Api.Client.ApiResponse<CountryResponse> localVarResponse = CreditsCountrycodeGetWithHttpInfo(countrycode);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  The credit cost for each SMS sent to the country code provided
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="countrycode">The 2-letter ISO country code of the country you want to retrieve the credit cost for.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CountryResponse</returns>
        public SMSWorks.Api.Client.ApiResponse<CountryResponse> CreditsCountrycodeGetWithHttpInfo(string countrycode, int operationIndex = 0)
        {
            // verify the required parameter 'countrycode' is set
            if (countrycode == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'countrycode' when calling CreditsApi->CreditsCountrycodeGet");
            }

            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("countrycode", SMSWorks.Api.Client.ClientUtils.ParameterToString(countrycode)); // path parameter

            localVarRequestOptions.Operation = "CreditsApi.CreditsCountrycodeGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<CountryResponse>("/credits/{countrycode}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreditsCountrycodeGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  The credit cost for each SMS sent to the country code provided
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="countrycode">The 2-letter ISO country code of the country you want to retrieve the credit cost for.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CountryResponse</returns>
        public async System.Threading.Tasks.Task<CountryResponse> CreditsCountrycodeGetAsync(string countrycode, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            SMSWorks.Api.Client.ApiResponse<CountryResponse> localVarResponse = await CreditsCountrycodeGetWithHttpInfoAsync(countrycode, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  The credit cost for each SMS sent to the country code provided
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="countrycode">The 2-letter ISO country code of the country you want to retrieve the credit cost for.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CountryResponse)</returns>
        public async System.Threading.Tasks.Task<SMSWorks.Api.Client.ApiResponse<CountryResponse>> CreditsCountrycodeGetWithHttpInfoAsync(string countrycode, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'countrycode' is set
            if (countrycode == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'countrycode' when calling CreditsApi->CreditsCountrycodeGet");
            }


            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("countrycode", SMSWorks.Api.Client.ClientUtils.ParameterToString(countrycode)); // path parameter

            localVarRequestOptions.Operation = "CreditsApi.CreditsCountrycodeGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<CountryResponse>("/credits/{countrycode}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreditsCountrycodeGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
