/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.11.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using SMSWorks.Api.Client;
using SMSWorks.Api.Model;

namespace SMSWorks.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOneTimePasswordApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve an OTP by it&#39;s message ID
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messageid">The ID of the OTP you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>OTPVerifyResponse</returns>
        OTPVerifyResponse OtpMessageidGet(string messageid, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve an OTP by it&#39;s message ID
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messageid">The ID of the OTP you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of OTPVerifyResponse</returns>
        ApiResponse<OTPVerifyResponse> OtpMessageidGetWithHttpInfo(string messageid, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Generate and send a One-Time Password
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otp">OTP properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>OTPResponse</returns>
        OTPResponse OtpSendPost(OTP otp, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Generate and send a One-Time Password
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otp">OTP properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of OTPResponse</returns>
        ApiResponse<OTPResponse> OtpSendPostWithHttpInfo(OTP otp, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Verify a One-Time Password
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passcode">One-Time Password</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>OTPVerifyResponse</returns>
        OTPVerifyResponse OtpVerifyPost(OTPVerify passcode, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Verify a One-Time Password
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passcode">One-Time Password</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of OTPVerifyResponse</returns>
        ApiResponse<OTPVerifyResponse> OtpVerifyPostWithHttpInfo(OTPVerify passcode, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOneTimePasswordApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve an OTP by it&#39;s message ID
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messageid">The ID of the OTP you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OTPVerifyResponse</returns>
        System.Threading.Tasks.Task<OTPVerifyResponse> OtpMessageidGetAsync(string messageid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Retrieve an OTP by it&#39;s message ID
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messageid">The ID of the OTP you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OTPVerifyResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<OTPVerifyResponse>> OtpMessageidGetWithHttpInfoAsync(string messageid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Generate and send a One-Time Password
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otp">OTP properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OTPResponse</returns>
        System.Threading.Tasks.Task<OTPResponse> OtpSendPostAsync(OTP otp, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Generate and send a One-Time Password
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otp">OTP properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OTPResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<OTPResponse>> OtpSendPostWithHttpInfoAsync(OTP otp, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Verify a One-Time Password
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passcode">One-Time Password</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OTPVerifyResponse</returns>
        System.Threading.Tasks.Task<OTPVerifyResponse> OtpVerifyPostAsync(OTPVerify passcode, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Verify a One-Time Password
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passcode">One-Time Password</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OTPVerifyResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<OTPVerifyResponse>> OtpVerifyPostWithHttpInfoAsync(OTPVerify passcode, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOneTimePasswordApi : IOneTimePasswordApiSync, IOneTimePasswordApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class OneTimePasswordApi : IOneTimePasswordApi
    {
        private SMSWorks.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="OneTimePasswordApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OneTimePasswordApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OneTimePasswordApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OneTimePasswordApi(string basePath)
        {
            this.Configuration = SMSWorks.Api.Client.Configuration.MergeConfigurations(
                SMSWorks.Api.Client.GlobalConfiguration.Instance,
                new SMSWorks.Api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = SMSWorks.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OneTimePasswordApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public OneTimePasswordApi(SMSWorks.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = SMSWorks.Api.Client.Configuration.MergeConfigurations(
                SMSWorks.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = SMSWorks.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OneTimePasswordApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public OneTimePasswordApi(SMSWorks.Api.Client.ISynchronousClient client, SMSWorks.Api.Client.IAsynchronousClient asyncClient, SMSWorks.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = SMSWorks.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public SMSWorks.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public SMSWorks.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SMSWorks.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SMSWorks.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Retrieve an OTP by it&#39;s message ID
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messageid">The ID of the OTP you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>OTPVerifyResponse</returns>
        public OTPVerifyResponse OtpMessageidGet(string messageid, int operationIndex = 0)
        {
            SMSWorks.Api.Client.ApiResponse<OTPVerifyResponse> localVarResponse = OtpMessageidGetWithHttpInfo(messageid);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Retrieve an OTP by it&#39;s message ID
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messageid">The ID of the OTP you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of OTPVerifyResponse</returns>
        public SMSWorks.Api.Client.ApiResponse<OTPVerifyResponse> OtpMessageidGetWithHttpInfo(string messageid, int operationIndex = 0)
        {
            // verify the required parameter 'messageid' is set
            if (messageid == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'messageid' when calling OneTimePasswordApi->OtpMessageidGet");
            }

            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("messageid", SMSWorks.Api.Client.ClientUtils.ParameterToString(messageid)); // path parameter

            localVarRequestOptions.Operation = "OneTimePasswordApi.OtpMessageidGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<OTPVerifyResponse>("/otp/{messageid}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OtpMessageidGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Retrieve an OTP by it&#39;s message ID
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messageid">The ID of the OTP you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OTPVerifyResponse</returns>
        public async System.Threading.Tasks.Task<OTPVerifyResponse> OtpMessageidGetAsync(string messageid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            SMSWorks.Api.Client.ApiResponse<OTPVerifyResponse> localVarResponse = await OtpMessageidGetWithHttpInfoAsync(messageid, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Retrieve an OTP by it&#39;s message ID
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="messageid">The ID of the OTP you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OTPVerifyResponse)</returns>
        public async System.Threading.Tasks.Task<SMSWorks.Api.Client.ApiResponse<OTPVerifyResponse>> OtpMessageidGetWithHttpInfoAsync(string messageid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'messageid' is set
            if (messageid == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'messageid' when calling OneTimePasswordApi->OtpMessageidGet");
            }


            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("messageid", SMSWorks.Api.Client.ClientUtils.ParameterToString(messageid)); // path parameter

            localVarRequestOptions.Operation = "OneTimePasswordApi.OtpMessageidGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<OTPVerifyResponse>("/otp/{messageid}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OtpMessageidGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Generate and send a One-Time Password
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otp">OTP properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>OTPResponse</returns>
        public OTPResponse OtpSendPost(OTP otp, int operationIndex = 0)
        {
            SMSWorks.Api.Client.ApiResponse<OTPResponse> localVarResponse = OtpSendPostWithHttpInfo(otp);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Generate and send a One-Time Password
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otp">OTP properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of OTPResponse</returns>
        public SMSWorks.Api.Client.ApiResponse<OTPResponse> OtpSendPostWithHttpInfo(OTP otp, int operationIndex = 0)
        {
            // verify the required parameter 'otp' is set
            if (otp == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'otp' when calling OneTimePasswordApi->OtpSendPost");
            }

            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = otp;

            localVarRequestOptions.Operation = "OneTimePasswordApi.OtpSendPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<OTPResponse>("/otp/send", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OtpSendPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Generate and send a One-Time Password
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otp">OTP properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OTPResponse</returns>
        public async System.Threading.Tasks.Task<OTPResponse> OtpSendPostAsync(OTP otp, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            SMSWorks.Api.Client.ApiResponse<OTPResponse> localVarResponse = await OtpSendPostWithHttpInfoAsync(otp, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Generate and send a One-Time Password
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="otp">OTP properties</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OTPResponse)</returns>
        public async System.Threading.Tasks.Task<SMSWorks.Api.Client.ApiResponse<OTPResponse>> OtpSendPostWithHttpInfoAsync(OTP otp, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'otp' is set
            if (otp == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'otp' when calling OneTimePasswordApi->OtpSendPost");
            }


            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = otp;

            localVarRequestOptions.Operation = "OneTimePasswordApi.OtpSendPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<OTPResponse>("/otp/send", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OtpSendPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Verify a One-Time Password
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passcode">One-Time Password</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>OTPVerifyResponse</returns>
        public OTPVerifyResponse OtpVerifyPost(OTPVerify passcode, int operationIndex = 0)
        {
            SMSWorks.Api.Client.ApiResponse<OTPVerifyResponse> localVarResponse = OtpVerifyPostWithHttpInfo(passcode);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Verify a One-Time Password
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passcode">One-Time Password</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of OTPVerifyResponse</returns>
        public SMSWorks.Api.Client.ApiResponse<OTPVerifyResponse> OtpVerifyPostWithHttpInfo(OTPVerify passcode, int operationIndex = 0)
        {
            // verify the required parameter 'passcode' is set
            if (passcode == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'passcode' when calling OneTimePasswordApi->OtpVerifyPost");
            }

            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = passcode;

            localVarRequestOptions.Operation = "OneTimePasswordApi.OtpVerifyPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<OTPVerifyResponse>("/otp/verify", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OtpVerifyPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Verify a One-Time Password
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passcode">One-Time Password</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OTPVerifyResponse</returns>
        public async System.Threading.Tasks.Task<OTPVerifyResponse> OtpVerifyPostAsync(OTPVerify passcode, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            SMSWorks.Api.Client.ApiResponse<OTPVerifyResponse> localVarResponse = await OtpVerifyPostWithHttpInfoAsync(passcode, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Verify a One-Time Password
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="passcode">One-Time Password</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OTPVerifyResponse)</returns>
        public async System.Threading.Tasks.Task<SMSWorks.Api.Client.ApiResponse<OTPVerifyResponse>> OtpVerifyPostWithHttpInfoAsync(OTPVerify passcode, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'passcode' is set
            if (passcode == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'passcode' when calling OneTimePasswordApi->OtpVerifyPost");
            }


            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = passcode;

            localVarRequestOptions.Operation = "OneTimePasswordApi.OtpVerifyPost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<OTPVerifyResponse>("/otp/verify", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OtpVerifyPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
