/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.
 *
 * The version of the OpenAPI document: 1.11.0
 * Contact: support@thesmsworks.co.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using SMSWorks.Api.Client;
using SMSWorks.Api.Model;

namespace SMSWorks.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUtilsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get error by code
        /// </summary>
        /// <remarks>
        /// Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ExtendedErrorModel</returns>
        ExtendedErrorModel UtilsErrorsErrorcodeGet(string errorcode, int operationIndex = 0);

        /// <summary>
        /// Get error by code
        /// </summary>
        /// <remarks>
        /// Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ExtendedErrorModel</returns>
        ApiResponse<ExtendedErrorModel> UtilsErrorsErrorcodeGetWithHttpInfo(string errorcode, int operationIndex = 0);
        /// <summary>
        /// Return the customer ID to the caller
        /// </summary>
        /// <remarks>
        /// A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TestResponse</returns>
        TestResponse UtilsTestGet(int operationIndex = 0);

        /// <summary>
        /// Return the customer ID to the caller
        /// </summary>
        /// <remarks>
        /// A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TestResponse</returns>
        ApiResponse<TestResponse> UtilsTestGetWithHttpInfo(int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUtilsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get error by code
        /// </summary>
        /// <remarks>
        /// Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExtendedErrorModel</returns>
        System.Threading.Tasks.Task<ExtendedErrorModel> UtilsErrorsErrorcodeGetAsync(string errorcode, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get error by code
        /// </summary>
        /// <remarks>
        /// Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExtendedErrorModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<ExtendedErrorModel>> UtilsErrorsErrorcodeGetWithHttpInfoAsync(string errorcode, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Return the customer ID to the caller
        /// </summary>
        /// <remarks>
        /// A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TestResponse</returns>
        System.Threading.Tasks.Task<TestResponse> UtilsTestGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Return the customer ID to the caller
        /// </summary>
        /// <remarks>
        /// A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </remarks>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TestResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TestResponse>> UtilsTestGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUtilsApi : IUtilsApiSync, IUtilsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UtilsApi : IUtilsApi
    {
        private SMSWorks.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UtilsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UtilsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UtilsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UtilsApi(string basePath)
        {
            this.Configuration = SMSWorks.Api.Client.Configuration.MergeConfigurations(
                SMSWorks.Api.Client.GlobalConfiguration.Instance,
                new SMSWorks.Api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = SMSWorks.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UtilsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UtilsApi(SMSWorks.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = SMSWorks.Api.Client.Configuration.MergeConfigurations(
                SMSWorks.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new SMSWorks.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = SMSWorks.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UtilsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public UtilsApi(SMSWorks.Api.Client.ISynchronousClient client, SMSWorks.Api.Client.IAsynchronousClient asyncClient, SMSWorks.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = SMSWorks.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public SMSWorks.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public SMSWorks.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public SMSWorks.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public SMSWorks.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get error by code Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ExtendedErrorModel</returns>
        public ExtendedErrorModel UtilsErrorsErrorcodeGet(string errorcode, int operationIndex = 0)
        {
            SMSWorks.Api.Client.ApiResponse<ExtendedErrorModel> localVarResponse = UtilsErrorsErrorcodeGetWithHttpInfo(errorcode);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get error by code Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ExtendedErrorModel</returns>
        public SMSWorks.Api.Client.ApiResponse<ExtendedErrorModel> UtilsErrorsErrorcodeGetWithHttpInfo(string errorcode, int operationIndex = 0)
        {
            // verify the required parameter 'errorcode' is set
            if (errorcode == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'errorcode' when calling UtilsApi->UtilsErrorsErrorcodeGet");
            }

            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("errorcode", SMSWorks.Api.Client.ClientUtils.ParameterToString(errorcode)); // path parameter

            localVarRequestOptions.Operation = "UtilsApi.UtilsErrorsErrorcodeGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ExtendedErrorModel>("/utils/errors/{errorcode}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UtilsErrorsErrorcodeGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get error by code Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ExtendedErrorModel</returns>
        public async System.Threading.Tasks.Task<ExtendedErrorModel> UtilsErrorsErrorcodeGetAsync(string errorcode, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            SMSWorks.Api.Client.ApiResponse<ExtendedErrorModel> localVarResponse = await UtilsErrorsErrorcodeGetWithHttpInfoAsync(errorcode, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get error by code Returns a sample error object for the given error code. Useful for designing code to react to errors when they occur for real.
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="errorcode">The code of the error you would like returned</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ExtendedErrorModel)</returns>
        public async System.Threading.Tasks.Task<SMSWorks.Api.Client.ApiResponse<ExtendedErrorModel>> UtilsErrorsErrorcodeGetWithHttpInfoAsync(string errorcode, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'errorcode' is set
            if (errorcode == null)
            {
                throw new SMSWorks.Api.Client.ApiException(400, "Missing required parameter 'errorcode' when calling UtilsApi->UtilsErrorsErrorcodeGet");
            }


            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("errorcode", SMSWorks.Api.Client.ClientUtils.ParameterToString(errorcode)); // path parameter

            localVarRequestOptions.Operation = "UtilsApi.UtilsErrorsErrorcodeGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ExtendedErrorModel>("/utils/errors/{errorcode}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UtilsErrorsErrorcodeGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Return the customer ID to the caller A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TestResponse</returns>
        public TestResponse UtilsTestGet(int operationIndex = 0)
        {
            SMSWorks.Api.Client.ApiResponse<TestResponse> localVarResponse = UtilsTestGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Return the customer ID to the caller A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TestResponse</returns>
        public SMSWorks.Api.Client.ApiResponse<TestResponse> UtilsTestGetWithHttpInfo(int operationIndex = 0)
        {
            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "UtilsApi.UtilsTestGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<TestResponse>("/utils/test", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UtilsTestGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Return the customer ID to the caller A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TestResponse</returns>
        public async System.Threading.Tasks.Task<TestResponse> UtilsTestGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            SMSWorks.Api.Client.ApiResponse<TestResponse> localVarResponse = await UtilsTestGetWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Return the customer ID to the caller A generic test method which can be used to verify that the API is up and that your calls are authenticated successfully
        /// </summary>
        /// <exception cref="SMSWorks.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TestResponse)</returns>
        public async System.Threading.Tasks.Task<SMSWorks.Api.Client.ApiResponse<TestResponse>> UtilsTestGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            SMSWorks.Api.Client.RequestOptions localVarRequestOptions = new SMSWorks.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json;charset=UTF-8"
            };

            var localVarContentType = SMSWorks.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = SMSWorks.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "UtilsApi.UtilsTestGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JWT) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<TestResponse>("/utils/test", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UtilsTestGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
